[SS]
url-irc = https://docs.google.com/spreadsheets/d
url-irc-sn = Sheet1
url-zn = https://docs.google.com/spreadsheets/d
url-zn-sn = Form Responses 1
wback = Ya

[DIR]
irc = E:\ADM IRC AND ZN\2026
zn = E:\ADM IRC AND ZN\2026
arvi = E:\ADM IRC AND ZN\ARVIEWER.xlsm

[WINGS]
irc-del = 2:19593
irc-hid = D:G
zn-del = 2:75
zn-hid = D:H
